---
title: ""
output:
  pdf_document:
    latex_engine: xelatex
header-includes:  
    - \usepackage{geometry} 
    - \usepackage{array, makecell}
biblatex: 1
biblio-style: authoryear,backend=biber
biblatexoptions: 
  - maxbibnames = 20
  - maxcitenames = 2
  - doi = false
  - isbn = false
  - giveninits = true
  - uniquelist = false
  - uniquename=init
bibliography: "bibliography.bib"
geometry: margin=1in 
fontsize: 12pt
documentclass: article
classoption: letterpaper
link-citations: true
font: "Times New Roman"
---




**Title of the Project**: Statistical Methods for Daily Mortality and Multiple Environmental Risk Factors

**Name and affiliations of lead investigators**

- Patrick E. Brown
    - Centre for Global Health Research, St. Michael's Hospital
    - Department of Statistical Sciences, University of Toronto
    - [pbrown.ca](http://www.pbrown.ca)
- Fateh Chebana 
    - Centre Eau Terre Environnement, Institut national de la recherche scientifique, Québec.
    - [inrs.ca/en/research/professors/fateh-chebana](https://inrs.ca/en/research/professors/fateh-chebana/)
- Cindy Feng 
    - Department of Community Health and Epidemiology, Dalhousie University
    - [medicine.dal.ca/departments/department-sites/community-health/our-people/our-faculty/cindy-feng.html](https://medicine.dal.ca/departments/department-sites/community-health/our-people/our-faculty/cindy-feng.html)
- Meredith Franklin 
    - Keck School of Medicine, University of Southern California (until July 2021) 
    - School for the Environment and Department of Statistical Sciences, University of Toronto (from July 2021)
    - [keck.usc.edu/faculty-search/meredith-franklin](https://keck.usc.edu/faculty-search/meredith-franklin/)


**List of collaborators, titles, and affiliations**

Name: Kamal Rai <br/>  
Title: PhD student<br/>  
Affiliations: Centre for Global Health Research, St. Michael's Hospital <br/>  
              \hspace*{61.5pt} Department of Statistical Sciences, University of Toronto


Name: Daniel Rainham <br/>   
Title: Professor <br/>    
Affiliations: School of Health and Human Performance, Dalhousie University <br/>    
              \hspace*{61.5pt} Healthy Populations Institute, Dalhousie University 

Name: Hwashin Shin <br/>  
Title: Scientist <br/>  
Affiliation: Environmental Health Science and Research Bureau, Health Canada <br/>  


Name: Prabhat Jha<br/>  
Title: Director<br/>  
Affiliation:  Centre for Global Health Research, St. Michael's Hospital<br/>  



Name: Céline Campagna <br/>  
Title: Responsable scientifique <br/>  
Affiliation: Équipe Changements climatiques et santé, Institut National de Santé Publique du Québec


Name: Pierre Masselot <br/>  
Title: Research Fellow <br/>    
Affiliation: London School of Hygiene & Tropical Medicine, United Kingdom


   

**List of partner organizations**

- The **Centre for Global Health Research, St. Michael's Hospital** will lead the health sciences research component of the project, providing data from the US and India and time of research staff to work on manuscripts. The Toronto-based component of the team will be located at the Centre for Global Health Research (CGHR) and will be integrated into the Geospatial Mortality research group Dr. Brown leads. A portion of the Toronto PhD student's salary will be funded though a CGHR research grant.

- **L'Institut National de Santé Publique du Québec** has the mandate to analyse, monitor and evaluate determinants of health, including environmental pollutants, and will give access to the Quebec provincial health databases. In-kind support will also include health expertise for the statistical design and interpretation of research, including co-supervision of students.

- Hwashin Shin at **Health Canada** is central to this project. Her needs for an improved air quality indicator instigated the discussions which lead to this application. Health Canada will provide detailed cause-specific daily mortality and morbidity counts. Dr. Shin has been funding Dr. Brown's team through Health Canada research contracts, and intends to continue doing so throughout this project.


\clearpage

# Research Aims

## Overview

There is growing interest in developing a simple, intuitive air quality index that combines multiple pollutants while simultaneously estimating their health effects [@dominici2010protecting; @stieb2008new; @bopp2018something]. Typically, health effects associated with exposure to air pollution focus on one pollutant at a time, but this ignores the fact that realistiaclly, exposures are complex mixtures of multiple pollutants [@dominici2010protecting]. Thus, an air quality index that reflects this complex mixture is needed and should account for the levels and relative contributions of multiple air pollutants together. In this proposal we present an improved statistical method that allows us to model multiple environmental pollutants while simultaneously estimating their health effects. With this method we are also able to conduct inference on the health effect estimates. We demonstrate our approach by focusing on quantifying the short-term health effects associated with air pollution mixtures at the population level.

The *constrained groupwise additive index model* (cGAIM), introduced by @hardle1993,
is a vehicle for providing a multi-pollutant health index. Given $\lambda_{it}$ representing a particular health outcome for an individual $i$ on day $t$,  the cGAIM is
$$
  \lambda_{it} = \exp\left[ X_{it}^{T}\beta + s(\alpha^{T} Z_{it} ) + f_{1}( W_{1it} ) + \ldots + f_{K}( W_{Kit} ) \right],
$$
where $\beta$ parameters are the fixed effects of the potentially time-varying linear covariates $X_{it}$, and $f_{1}, \ldots, f_{K}$ are smooth functions that account for potentially non-linear covariates or confounders $W_{kit}$ ($k = 1 \ldots K$). The distinguishing feature of cGAIM is the smooth function $s$ whose argument is a linear combination of variables $Z_t$, for example fine particulate matter (PM$_{2.5}$) and ozone (O$_3$). The $\alpha$ parameter is a vector of estimated weights on the entries of $Z_t$, and gives their relative contributions. The smooth functions $s$ and the $f_k$ might be composed of spline functions or Gaussian processes such as random walks.  

To date, cGaim has been developed for Poisson models, namely where the outcome is case counts (e.g. number of asthma-related hospital visits in a county). We will expand its usage to case crossover models, which have seen increased attention in the air pollution literature [@wei2019short; @stringer2020approximate].  In case crossover models we can examine individual-level data, whereby the exposure on an event or case day is compared to the exposure on referent or *control days* for each case. For example, the air polution concentrations on a day of an individual's hospital visit will be conditioned on the same individual's exposure on pre-selected control days, perhaps chosen as the air pollution concentrations on same day of the week from the previous two weeks. Case crossover models use a partial likelihood for the probability the event occurs on the case day rather than the control days. The advantage of case crossover models is that individual-level confounders are automatically adjusted for, as are risk factors which vary slowly or not at all, or are the same on the case and control days.  The challenge introduced by case crossover models is the likelihood depends on non-linear combinations of the latent variables (i.e. $s$). 


Estimating $\alpha$ is the main statistical challenge with the cGAIM, which @pierre2020aim 
accomplish with frequentist inference methods that use sequential quadratic programming.  We will develop a Bayesian methodology for inference with the cGAIM --- the bcGAIM --- which will estimate and fully quantify the uncertainty around $\alpha$ as well as propagate the uncertainty into inference on $s$.  

The bcGAIM will also able to efficiently handle higher dimensional $\alpha$ and $Z_{it}$, which is a significant improvement over cGAIM and an important feature of the model as we aim to model complex multi-pollutant mixtures.


## Outcomes and applications

This project brings together the methodological components of several interdisciplinary and collaborative research activities in which the four investigators have independently been engaged.  

The primary driver of this research is the need for an improved air quality warning system, which Health Canada and the Institut national de santé publique du Québec have separately approached Drs Brown and Chebana (respectively) about.  Currently the Canadian AQHI is composed of relative risks estimated from cohort studies, and estimated risks for individual pollutants are summed to create a log-relative risk which is in turn converted to a 10-point scale.  This is likely to over-estimate risk,  @franklin2008impact found that the effect of ozone on non-accidental mortality was "substantially reduced" after adjusting for particle sulfate and @liu2019ambient found significant differences in the percentage change of all-cause mortality attributable to PM~2.5~ and PM~10~ after adjusting for NO~2~ or SO~2~. Furthermore, there is evidence that some health outcomes are nonlinearly related to pollution measurements [@feng2016impact].  Dr. Brown's group has developed a linear multi-pollutant case/crossover model [@guowen2020multi] whereas Dr. Chebana's has used a cGAIM with a frequentist time series model [@pierre2020aim].  The proposed bcGAIM is a natural extension of, and merging of, these two methods.  

A second driver of this project is the environmental epidemiology research undertaken by the investigators in collaboration with health science researchers.  The Centre for Global Health Research, where Dr. Brown is partly based, has history of producing papers on global mortality in high-impact journals.  The Million Deaths Study in India has 13 years worth of cause-specific mortality data geocoded to point locations and with smoking and diet information about the deceased and from healthy respondents.  Dr. Franklin has a number of highly cited papers on air quality and mortality in environmental health journals.  With our collaborators, including Prabhat Jha in Toronto and Daniel Rainham at Dalhousie, we will use bcGAIM to produce papers for the top-ranked medical journals.

The third motivation for this CRT is the surge in availability of daily mortality data brought on by the COVID-19 pandemic.
The relationship between daily COVID-19 deaths and air pollution levels has recently become an active area of research.  @wu2020exposure find that a 1 $\mu$g increase in long-term exposure to ambient PM~2.5~ increases the COVID-19 mortality rate by 15%.  We will relate COVID-19 incidence and mortality to air pollution in major urban centres worldwide, where possible focusing on deaths outside long-term care homes.  


A key reason the bcGAIM model is ideal for the above problems is it will produce parameters which are interpretable.  The $\alpha$ coefficients give the relative importance of each pollutant (at each lag), and $s(\cdot)$ is the relative risk from a basket of exposures.  Unsupervised methods such as principal components analysis and clustering can be difficult to interpret [@davalos2017current]. A popular nonparametric method is Bayesian Kernel Machine Regression (BKMR), which models an exposure-response surface via a kernel function [@bobb2015bayesian]. Using a hierarchical Bayesian variable selection method, it can select one pollutant from a group of correlated ones, and is interpreted by visualizing cross-sections of a potentially high-dimensional exposure-response surface. The bcGAIM will provide similar flexibility to the BKMR, while being able to meet the communication needs of inter-disciplinary research teams.

## Methods

The bcGAIM will make four methodological advancements for modeling  health effects of mixtures of exposures. These are:

1. develop bcGAIM, a Bayesian inference methodology for high dimensional cGAIM's in case-crossover models;
1. create an efficient, non-iterative computational algorithm for bcGAIM's based on Laplace approximations;
1. develop non-parametric forms of the dose-response effect which encourage or enforce monotonicity; and
1. engage in interdisciplinary and applied research projects with our subject-area collaborators.

### Model

A simple two-pollutant version of bcGAIM has been implemented by Dr. Brown's group (under contract from Health Canada) in the MCMC software Stan [@carpenter2017stan] with a Poisson response variable.  This will be extended to having an $\alpha$ which is 12- or 15-dimensional, with three pollutants (O~3~, PM~2.5~, and NO~2~) at time lags of up to five days.  Converting the Poisson likelihood to case-crossover, moving to a highly-parallelized cloud platform, and increasing the dimensionality will initiallyrequire only modest amount of additional coding, although the algorithm is unlikely to function properly without a substantial amount of further modification and optimization.  This is because we expect that $\alpha$ will not always be well identified, and the results will be sensitive to parametrizations and prior distributions. 

The major task in this component of the research will be to find reparametrizations and multivariable prior distributions that enable prior elicitation from subject-area specialists.  We will adopt the penalized complexity prior framework of @simpson2017penalising, specifying a base model with some suitably chosen values $\alpha_0$ and deriving a prior for $\alpha$ which corresponds to an exponential prior on the KL distance between $s(\alpha Z)$ and $s(\alpha_0 Z)$.  Expert advice will be used to set $\alpha_0$ and the rate of the exponential prior.  One possible scenario would be to have $\alpha_0$ with an entry of $1$ for PM~2.5~ at lag 1 and zero otherwise, and an extremely strong exponential prior on the KL distance.  This prior would encourage a conventional single-pollutant single-lag model, other pollutants would be inferred to have negligible effect on health outcomes unless the data provided considerable information to the contrary.  A weaker prior with $\alpha_0$ having multiple non-zero entries would allow for stronger multi-pollutant effects.   Box constraints, such as the entries of $\alpha$ being positive, should be relatively simple to implement.

Anticipating that the posterior of $\alpha$ will often have flat ridges, interpreted as overall pollution is known to be harmful but specific components may or may not be, communicating results to health scientists will be challenging.  Finding intuitive and interpretable low-dimensional functions of $\alpha$ which convey the 'known' and 'unknown' components of the results will be a second important task in this objective.



### Computation

For the second methodological aim, we will develop non-MCMC inference methods similar in spirit to INLA [@rue2009approximate]. Case-crossover models are not compatible with the original INLA methodology, and an INLA-like algorithm for these models was recently developed by @stringer2020approximate and further improved in @noeps.  The Latent Gaussian approximation in INLA separates the parameter space into covariance parameters $\theta$ and linear predictors $\eta = (\beta, \theta, f)$, and considers $\pi( \eta | Y, \theta)$, $\pi( \theta | Y)$, and $\pi(\eta | Y) = \int \pi(\eta | Y, \theta) \pi(\theta | Y) d\theta$ (the last one numerically). INLA performs approximate inference on $\theta$ by estimating $\phi( \theta | Y, \phi )$ with a normal distribution with mean $\theta^{*}$ and variance $\Sigma^{*}$. 


Let us translate this reasoning to the bcGAIM, which has link function $g(\lambda_{t}) = X^{t}\beta + s( \alpha^{T} Z_{t}) + f_{1}(W_{1,t}) + \ldots + f_{K}(W_{K,t})$. Note that conditional on $\alpha$, $\alpha^{T}Z_{t}$ is known. Thus, we can simplify the estimation problem by considering parameters $\phi$, $\theta$, and $\alpha$ and estimating $\pi( \eta | Y, \theta, \alpha)$, $\pi( \alpha | Y, \theta )$, $\pi(\theta | Y)$, and $\pi(\eta | Y) = \int \pi(\eta | Y, \theta, \alpha) \pi( \alpha | Y, \theta ) \pi( \theta | Y) d\theta d\alpha$ (the last one numerically). The first and third densities in the integrand, $\pi(\eta | Y, \theta, \alpha)$ and $\pi( \theta | Y)$ are well-suited to the Laplace approximation while $\pi(\alpha | Y,\theta )$ can be estimated using HMC. Introducing two Laplace approximations will lessen the computational burden, and enable us to fit a hierarchical bcGAIM model to air pollution data. This will allow us to produce national estimates of air quality while fitting the bcGAIM to over 25 regions across Canada, each with over 6,000 daily observations, an otherwise daunting computational task. Therefore, this non-MCMC inference method will provide significant computational and ease-of-use benefits, and will expand the types of problems and number of users who can use the bcGAIM methodology. To facilitate use by other researchers, all bcGAIM software will be released in an R package.




### Monotonicity

The third methodological aim will consider ways of encouraging (or forcing) the relative risk function $s(\cdot)$ to be monotonic.  Monotonicity for non-parametric smoothing was formalized by @ramsay1988monotone, and an early example of monotonic additive index models is @xia2006cumulative.   The cGAIM from @pierre2020aim allows for any linear constraint on $\alpha$ and different shape constraints on $s$ including monotonicity, convexity, and concavity. For frequentist inference monotonicity can be incorporated as a restriction of the parameter space during optimization, whereas Bayesian inference involves integrating out all possible realizations of $s$ (not only the mode).  @golchi2015monotone state "While a rich literature exists on monotone function estimation, interpolation of monotone functions with uncertainty quantification remains an understudied topic." For this reason much of the previous literature on additive index models is not relevant to the development of bcGAIM.  

Initially we will consider different Gaussian processes for $s$ which are more likely to be monotonic than random walks, such as a first-order random walk plus drift.  Reparametrizations of higher-order random walks with suitably chosen priors for the boundary values (i.e. first and last point for RW2's) could also produce random functions with a low probability of having local optima.  A more sophisticated approach is offered by @golchi2015monotone, where sequential constrained Monte Carlo is used to take posterior samples from a process with positivity constraints on the derivatives.

Finally, consider an approach similar in spirit to bcGAIM. @burkner2020modelling propose a Bayesian model to estimate ordinal predictors with monotonic effects. They employ a simplex parameter $\zeta$ to model normalized differences between categories, and a scale parameter $b$. The prior on $b$ expresses prior knowledge on the average differences between adjacent categories, while the prior on $\zeta$ expresses prior knowledge on individual differences between adjacent categories. The authors suggest an $N(0,\sigma)$ prior on $b$ and a $\text{Dirichlet}(\alpha)$ prior on $\zeta$. Then, $\sigma$ and $\alpha$ would express how heavily average and individual differences between adjacent categories are penalized. Not only are $\zeta$ and $b$ interpretable, but so are the prior parameters $\sigma$ and $\alpha$. The bcGAIM seeks to achieve this ease of interpretation of its parameters and priors. This will encourage adoption of the bcGAIM in other research areas, which is one of the goals of this project.



### Applications

In a highly cited paper with many eminent co-authors, @liu2019ambient estimate short-term effects of PM~2.5~ on mortality in 652 cities and produce a pooled global estimate.  All-cause mortality risk is shown to be roughly 4% higher at $100\mu g/m^3$ than at $5\mu g/m^3$, with the curve steeper at low values than higher values.  A Poisson time series model with regression splines was used. We will reproduce this analysis in as many cities as possible using bcGAIM, improving on @liu2019ambient by using case-crossover models, monotonic semi-parametric models, and accounting for the combined effects of multiple pollutants.  

COVID-19 incidence and mortality counts have been made publicly available for many countries, much of the data are available sub-nationally, with age and sex information, and for individuals in and outside of nursing homes.  While incidence data are both incomplete and with a level of completeness varying spatio-temporally, better measures of incidence will become available from antibody studies.  The Centre for Global Health Research runs the Action to Beat Coronavirus study ([abcstudy.ca](http://abcstudy.ca)), which started collecting blood samples from a representative sample of the Canadian population in May 2020.  As of October, 8000 samples have been returned and a second round of testing is underway.  With repeated samples an estimate of true incidence over time can be obtained and changes in under-reporting inferred.  We will use bcGAIM to quantify the effect of air quality on COVID-19 incidence, mortality, and the case fatality rate.

<!-- 
**References**
Source: https://stackoverflow.com/questions/46738721/how-can-i-bring-back-indentation-workaround-in-rmarkdown-pandoc-genuine-referenc
\setlength{\parskip}{1pt}
<div id="refs"></div>
\setlength{\parskip}{8pt}
 -->

\printbibliography


\clearpage
**Anticipated roles of trainees (students and post-doctoral fellows)**

<!-- Describe roles of undergraduate and graduate students and postdoctoral fellows in the project. Indicate the proposed home institution of the various personnel, how they will be mentored and included in the project, and how they would contribute to the cohesion of the team (e.g. through joint supervision arrangements). Limit to one page. --> 

**THIS NEEEDS TO BE UPDATED TO MATCH THE RESPONSE TO THE SAC's QUESTIONS**

Kamal Rai will complete his PhD in 2021 and will work on this project as a postdoc.  He will develop the Bayesian implementation of the GAIM models in Stan. This includes exploring determining appropriate prior distributions for the weights $\alpha$, developing visualizations that communicate modeling results, and assisting other project members in developing shape constraints. He will be responsible for producing paper(s) summarizing the results of this model when run on Canadian air pollution and mortality data. To facilitate team communication and cohesion, he will also split time between Toronto (at the Centre for Global Health Research) and Ottawa (at the University of Ottawa), and use the proximity of the University of Ottawa to Quebec to occasionally visit project collaborators located there.

The University of Toronto PhD student will develop the INLA-like Bayesian computations to conduct inference on the GAIM, and compare its results from those obtained from the Stan implementation. A University of Laval or University of Ottawa PhD student will develop methods to conduct shape-constrained (Bayesian) inference, and examine the relationship between COVID-19 deaths and air pollution levels. 


**Equity, Diversity, Inclusion**

<!-- Explain how the project addresses the EDI priorities of NSERC and CANSSI (http://www.canssi.ca/home/a-note-on-diversity). Limit to half a page. --> 

**THIS NEEDS TO BE COMPLETED**

**Anticipated organization of collaboration**

<!-- Describe plans for supporting collaboration, e.g. indicating how members of the team would communicate, group meetings, exchanges of students and postdoctoral fellows, dealing with disciplinary and geographic hurdles to the collaboration. Limit to one page. --> 

**THIS NEEEDS TO BE UPDATED TO MATCH THE RESPONSE TO THE SAC's QUESTIONS**

The research team is situated in three cities - Toronto, Quebec, and Halifax. Two investigators, Patrick Brown and Meredith Franklin, will be in Toronto at the University of Toronto. One investigator and one collaborator, Cindy Feng and Daniel Rainham, will be in Halifax at Dalhousie University. Finally, one investigator, Fateh Chebana, will be in Quebec at INRS.


**Plans for dissemination and communication**

<!-- Describe plans for dissemination and communication, e.g., organization of specialized professional meetings, organized presentations at large professional meetings, preparation of short courses, surveys, and notes, software, publicly accessible publications, and so on, expanding on the description in the Letter of Intent. Limit to half a page. -->

**THIS NEEDS TO BE UPDATED**

The lead investigators of this proposal have a track record of publishing research results in leading statistical and epidemiological journals, and aim to publish the results of this project in high-impact journals. The results and findings of this multiple pollutant inquiry will also be shared with Health Canada and the Institut National de Santé Publique du Québec.   Drs Shin and Campagna will use the methodologies developed in their ongoing research and programatic work, and facilitate the adoption of the methods more widely in their organizations.


**Schedule of events** 

<!-- Provide a three-year calendar or schedule of major collaborative activities, dissemination and publication activities, and any project milestones. --> 

**THIS NEEDS TO BE UPDATED**

\underline{Project Milestones}

Task: Develop the bcGAIM 

\begin{itemize}
    \item 6-8 months: Implement prior(s) for shape-constrained inference for 1$^{\text{st}}$-order and 2$^{\text{nd}}$-order random walks. 
    \item 8-12 months: Implement the bcGAIM in Stan and apply to the multi-pollutant problem. 
    \item 12-16 months: Iterate development of priors until modeling results are satisfactory for the multi=pollutant model.
    \item 16-20 months: Write a paper summarizing these modeling results and submit for publication. 
    \item 16-20 months: Release an R package so that these models are readily available.
    \item 20-24 months: Implement additional prior(s) for shape-constrained Bayesian inference.
    \item 24-30 months: Extend to a hierarchical model. 
    \item 30-36 months: Write a paper summarizing the results of the hierarhical extensions for the exact and approximate inference models, and submit for publication. 

\end{itemize}

Task: Approximate Inference Algorithm
\begin{itemize}
    \item 4-6 months: Implement Laplace approximations for $\pi( \eta | \theta, \alpha, Y )$ and $\pi( \theta | Y )$ in Stan. 
    \item 4-8 months: Implement an approximate inference algorithm for $\pi( \alpha | \theta,Y )$ in Stan. 
    \item 8-12 months: Implement both approximations outside of Stan. Compare estimation results to those achieved in Stan.
    \item 12-16 months: Iterate development of approximation schemes outside of Stan.
    \item 16-20 months: Write a paper summarizing these results and submit for publication. 
    \item 20-24 months: Apply both approximations to the multi-pollutant model.
    \item 20-24 months: Add the approximate Bayesian inference models to the R package. 
    \item 24-30 months: Extend the approximation algorithm to hierarchical models. Compare to results obtained by Stan.
    \item 30-36 months: Add hierarchical approximate inference model to the R package. 
\end{itemize}


Task: Multi-Pollutant Application

Note: The Stan implementation of the bcGAIM and the approximate inference algorithms will be developed against the multi-pollutant model, so the tasks for this application are mostly listed above. We include it on its own to give a specific breakdown of the development of the mulit-pollutant model.

\begin{itemize}
    \item 8-12 months: Explore the performance of bcGAIM across regions and mortality outcomes.
    \item 12-16 months: Iteratively refine the bcGAIM (including the shape-constraining priors).
    \item 24-30 months: Extend the multi-pollutant model to a hierarchical model (exact and approximate versions).
    \item 30-36 months: Write a paper summarizing these results and submit for publication. 
    \item 30-36 months: Add hierarhical bcGAIM model to the R package.
\end{itemize}


Task: COVID-19 Application 
\begin{itemize}
    \item 12-14 months: Identify COVID-19 confounders and data sets that may be used to fit a COVID-19 bcGAIM model. 
    \item 14-16 months: Fit the bcGAIM model to COVID-19 mortality data. 
    \item 16-20 months: Write a paper summarizing these results and submit for publication. 
\end{itemize}


Task: Collaborative Applications
\begin{itemize}
    \item 12-36 months: Once the bcGAIM is implemented, work with collaborations on appropriate epidemological studies.
\end{itemize}


**Dissemination and Publication Activities**

**THIS NEEDS TO BE UPDATED**

Year 1 

\begin{itemize}
  \item Milestone: Implement the bcGAIM with shape-constrained priors that are applicable for the multi-pollutant problem. 
  \item Milestone: Implement the INLA-like approximation to the target density of this model in Stan.
\end{itemize}

Year 2 

\begin{itemize}
    \item Milestone: 
    \item Milestone: 
    \item Submit paper: A multi-pollutant air quality index. 
    \item Submit Paper: Approximate Bayesian inference for the bcGAIM model
    \item Dissemination: Discuss shape-constrained Bayesian inference at 1-2 conferences.
    \item Dissemination: Discuss approximate Bayesian inference at 1-2 conferences. 
\end{itemize}

Year 3 

\begin{itemize}
    \item Milestone: 
    \item Submit Paper: Shape-constrained Bayesian inference with interpretable priors.
    \item Submit paper: The effects of multiple pollutant mixtures on COVID-19 mortality.
    \item Submit paper: A hierarchical extension to Approximate Bayesian inference
    \item Dissemintation: Discuss the multi-pollutant air quality index at 1-2 conferences.
    \item Dissemintation: Discuss hierarchical extensions to the multi-pollutant air quality index at 1-2 conferences.
    \item Dissemintation: Discuss the COVID-19 inquiry into air pollution exposure at 1-2 conferences.
\end{itemize}


\clearpage

**Major Collaborative Activities**

**THIS NEEDS TO BE UPDATED**

The different components of the bcGAIM project are naturally related. The bcGAIM is being developed in Stan in the first year, as is the first version of the approximate inference algorithm. Therefore, the bcGAIM model should be written to faciliate incorporating these approximations, and they should be developed knowing they will be implemented in Stan. In the second year, the two Stan models and the approximate inference algorithm will be extended to a hierarchical formulation. Although the hierarchical structure is at the city-level, nearby cities differ in their distance from each other. Ideally, a hierarchical model should account for how the composition of a mixture of pollutants varies by distance. The numerical difficulties and more complicated hierarchical structure should encourage strong collaboration at this stage of the project. The third year is devoted to applications -- applying the fully developed bcGAIM model to the multi-pollutant problem, COVID-19 data, and other epiodemiological applications that arise during the course of the project -- as well as writing papers and producing a useful R package. There is again natural collaboration between those writing and maintaining the R package. 



**Three-year budget**

**THIS NEEDS MILD UPDATES - I CAN DO THESE**

<!-- Provide a tentative three-year budget table showing the expenditures in each of the three years for undergraduate and graduate student funding, postdoctoral fellow funding, student travel, visitor travel, and costs associated with dissemination and publication of results. For each item, indicate the funding from CANSSI and the funding from other sources if applicable. If relevant, identify other sources of funding in footnotes below the table. CANSSI funding can be used only for NSERC eligible expenses. For the competition in 2020, the CANSSI funding over the three years should sum to $200,000. --> 

The table below lists income and expenses for each of the three years of the project. This budget assumes that CANSSI funding over the 3 year period is \$200,000. 

```{r CANSSI-Budget-Yearly-Breakdown, echo = FALSE}
library(magrittr) 
Expenses <- t( data.frame( "\\makecell[l]{Postdotor-\\\\al Fellow}", 
                           "\\makecell[l]{Graduate \\\\ Students}",
                           "\\makecell[l]{Graduate \\\\ Students}",
                           "\\makecell[l]{Undergrad \\\\ Students}",
                           "\\makecell[l]{Undergrad \\\\ Students}",
                           "\\makecell[l]{Research \\\\ Assistant}",
                           "\\makecell[l]{INSPQ \\\\ Staff Time}",
                           "Travel",
                           "\\textbf{Total}" ) )

Contributions_1_Names_Non_CANSSI <- t( data.frame( "HC",
                                        "INRS", 
                                        "NSERC", 
                                        "USRA",
                                        "DG",
                                        "CGHR",
                                        "INSPQ",
                                        " ",
                                        "  ") )

Contributions_1_CANSSI <- t( data.frame( "\\makecell[c]{\\$35}",
                                         "\\makecell[c]{ \\textcolor{white}{0} \\$24}",
                                         "\\makecell[c]{ \\textcolor{white}{0} \\$24}",
                                         "\\textcolor{white}{1-1}",
                                         "\\textcolor{white}{1-1}",
                                         "\\textcolor{white}{1-2}",
                                         "\\textcolor{white}{1-3}",
                                         "\\makecell[c]{\\$7}",
                                         "\\makecell[c]{\\textbf{\\$66}}" ) )

Contributions_2_CANSSI <- t( data.frame( "\\makecell[c]{\\$35}",
                                         "\\makecell[c]{ \\textcolor{white}{0} \\$24}",
                                         "\\makecell[c]{ \\textcolor{white}{0} \\$24}",
                                         "\\textcolor{white}{1-1}",
                                         "\\textcolor{white}{1-1}",
                                         "\\textcolor{white}{1-2}",
                                         "\\textcolor{white}{1-3}",
                                         "\\makecell[c]{\\$7}",
                                         "\\makecell[c]{\\textbf{\\$66}}" ) )

Contributions_3_CANSSI <- t( data.frame( "\\makecell[c]{\\$35}",
                                         "\\makecell[c]{ \\textcolor{white}{0} \\$24}",
                                         "\\makecell[c]{ \\textcolor{white}{0} \\$24}",
                                         "\\textcolor{white}{1-1}",
                                         "\\textcolor{white}{1-1}",
                                         "\\textcolor{white}{1-2}",
                                         "\\textcolor{white}{1-3}",
                                         "\\makecell[c]{\\$9}",
                                         "\\makecell[c]{\\textbf{\\$68}}" ) )

Contributions_1_Non_CANSSI <- t( data.frame( "HC: \\space \\space \\space \\space \\space \\$20",
                                         "INRS: \\space \\space \\$10",
                                         "NSERC: \\$7",
                                         "USRA:  \\space  \\space \\$9",
                                         "DG:  \\space  \\space  \\space  \\space  \\space  \\space \\$3",
                                         "CGHR: \\$10",
                                         "INSPQ: \\$10",
                                         " ",
                                         "\\makecell[l]{ \\textcolor{white}{0} \\space \\space \\space \\space \\space \\space \\space \\space \\space \\space \\textbf{\\$69}}" ) )

Contributions_1_Non_CANSSI[1] <- paste0("HC\\textbf{", kableExtra::footnote_marker_number(1), "}",
                                        " \\space \\space \\space \\space \\space \\space \\$20")                               
Contributions_1_Non_CANSSI[2] <- paste0("INRS\\textbf{", kableExtra::footnote_marker_number(2), "}",
                                        " \\space \\space \\space \\$20")                                     
Contributions_1_Non_CANSSI[3] <- paste0("NSERC\\textbf{", kableExtra::footnote_marker_number(3), "}", 
                                        " \\space \\$7" )
Contributions_1_Non_CANSSI[4] <- paste0("USRA\\textbf{", kableExtra::footnote_marker_number(4), "}", 
                                        " \\thinspace \\thinspace \\space \\space \\$9" )
Contributions_1_Non_CANSSI[5] <- paste0("DG\\textbf{", kableExtra::footnote_marker_number(5), "}",
                                        " \\thinspace \\space \\space \\space \\space \\space  \\space \\$3")
Contributions_1_Non_CANSSI[6] <- paste0("CGHR\\textbf{", kableExtra::footnote_marker_number(6), "}", 
                                        " \\thinspace \\thinspace \\$10")
Contributions_1_Non_CANSSI[7] <- paste0("INSPQ\\textbf{", kableExtra::footnote_marker_number(7), "}", 
                                        " \\thinspace \\thinspace \\$10")

Contributions_2_Non_CANSSI <- t( data.frame( "HC \\space \\space \\space \\space \\space \\space \\space \\space \\$20",
                                         "INRS \\space \\space \\space \\space \\space \\$10",
                                         "NSERC \\space \\space \\space \\$7",
                                         "USRA \\space \\space \\space \\space \\space \\$9",
                                         "DG \\space \\space \\space \\space \\space  \\space  \\space  \\space  \\space \\$3",
                                         "CGHR \\space \\space \\space \\$10",
                                         "INSPQ \\space \\space \\space \\$10",
                                         " ",
                                         "\\makecell[l]{ \\textcolor{white}{0} \\space \\space \\space \\space \\space \\space \\space \\space \\space \\space \\textbf{\\$69}}" ) )

Contributions_3_Non_CANSSI <- t( data.frame( "HC \\space \\space \\space \\space \\space \\space \\space \\space \\$20",
                                         "INRS \\space \\space \\space \\space \\space \\$10",
                                         "NSERC \\space \\space \\space \\$7",
                                         "USRA \\space \\space \\space \\space \\space \\$9",
                                         "DG \\space \\space \\space \\space \\space  \\space  \\space  \\space  \\space \\$3",
                                         "CGHR \\space \\space \\space \\$10",
                                         "INSPQ \\space \\space \\space \\$10",
                                         " ",
                                         "\\makecell[l]{ \\textcolor{white}{0} \\space \\space \\space \\space \\space \\space \\space \\space \\space \\space \\textbf{\\$69}}" ) )


Budget_Table <- cbind( Expenses, Contributions_1_CANSSI, 
                                 Contributions_1_Non_CANSSI, 
                                 Contributions_2_CANSSI, 
                                 Contributions_2_Non_CANSSI,
                                 Contributions_3_CANSSI, 
                                 Contributions_3_Non_CANSSI )
colnames(Budget_Table) = c( "", "CANSSI", "Non-CANSII", 
                                "CANSSI", "Non-CANSSI", 
                                "CANSSI", "Non-CANSSI" )
rownames(Budget_Table) = NULL 

knitr::kable( Budget_Table, booktabs = TRUE, escape = FALSE,
              format = "latex",  label = "Budget-Table" ) %>%
kableExtra::row_spec(0, align = "l") %>%
kableExtra::column_spec( c(1,3,5,7), border_right = TRUE) %>%
kableExtra::column_spec( c(1,2), border_left = TRUE) %>%
kableExtra::collapse_rows(columns = c(1,2,4,6)) %>%
kableExtra::add_header_above( c(" " = 1, "Year 1" = 2, "Year 2" = 2, "Year 3" = 2) ) %>%
kableExtra::add_header_above( c("Expenses" = 1, "Contributions (in 1,000's)" = 6) ) %>%
kableExtra::footnote(number = c( "HC: Health Canada", "INRS: Institut national de la recherche scientifique", "NSERC: The Natural Sciences and Engineering Research Council of Canada", "USRA: NSERC Undergraduate Student Research Award", "DG: NSERC Discovery Grant", "CHGR: Centre for Global Health Research", "INSPQ: Institut national de santé publique du Québec (Quebec Public Health Institute)" ))
```

\underline{Annual Expenses}

\begin{enumerate}
    \item Postdoctoral Fellow: The postdoctoral fellow will be funded from the CANSSI CRT grant and Health Canada. He will help organize team meetings, split time between Toronto and Halifax, and help onboard other students as they join the project. 
    
    \item Graduate Students: 1 PhD student and 1 Master's student will be involved in this project. One of the graduate students will be based at INRS, the other will be at the University of Toronto or Dalhousie University.  

    \item URSA Students: This project will have a number of self-contained projects suitable for undergraduate research assistants. We intend to involve 2 URSAs at \$6,000/year each, whose work will directly contribute to the project's research aims.
    
    \item Research Assistant: Hana Fu at CGHR will contribute roughly 3 days/month to the project. She will help maintain project data files and perform preliminary analysis. 
    
    \item INSPQ Staff Time: Céline Campagna at INSPQ will devote 0.5 days/week to the project. 
    
    \item Travel/Equipment: The travel expenses will cover attending conferences and travel between the three institutions by the project trainees. The equipment spending is intended to cover new computing equipment or cloud computing costs. 
\end{enumerate}

\underline{Contributions}

\begin{enumerate}
    \item CANSSI: The CANSSI funding is \$200,000 over three years, or \$66,666 per year. 
    
    \item Health Canada: Health Canada will contribute \$20,000 per year via research contracts. 
    
    \item INRS: Fateh Chebana will contribute \$10,000 in graduate student funding.
    
    \item NSERC: Cindy Feng will contribute \$7,000/year in graduate student funding. 
    
    \item INSPQ: The INSPQ will contribute staff time to the project, estimated at \$10,000/year for 3 years.
    
    \item CGHR: CGHR's support will be in-kind, in the form of funding the research assistant and providing research facilities.
    
    \item Undergraduate Summer Students: Two USRAs will be applied for each year, which will pay for undergraduate summer students. NSERC also requires a contribution from the Discovery Grant of the supervisor. 
\end{enumerate}